In [1]:
# 基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。
import numpy as np

my_arr = np.arange(1000000)

my_list =list(range(1000000))

In [2]:
%time for _ in range(10) : my_arr2 = my_arr * 2

Wall time: 92.8 ms


In [4]:
%time for _ in range(10) : my_list2 = [x * 2 for x in my_list]

Wall time: 1.33 s


In [6]:
# NumPy最重要的一个特点就是N维数组对象

data = np.random.randn(2,3)

data

array([[-0.40391044,  0.59093665, -0.01028764],
       [-0.24109797,  0.0992235 , -0.96354047]])

In [8]:
# ndarray 是一个通用的同构数据多维容器
# 每个数组都有一个shape(一个表示各维度大小的元组)
# dtype (一个用于说明数组数据类型的对象)

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
# 创建ndarray
# 最简单地方法是使用array函数

data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
# 嵌套序列将会被转换成一个多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# ndim 指的是array的维度

arr2.ndim

2

In [15]:
# np.array会尝试为新建的这个数组推断出一个较为合适的数据类型
arr2.dtype

dtype('int32')

In [16]:
# 除np.array之外,还有一些函数也可以新建数组
# 比如 zeros和ones可以创建指定长度或形状的全0或全1数组
# empty可以创建一个没有任何具体指的数组

# np.zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10).dtype

dtype('float64')

In [24]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
# 不一定返回全0,可能是未初始化的垃圾数据
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
np.empty((2,3))

array([[0.40391044, 0.59093665, 0.01028764],
       [0.24109797, 0.0992235 , 0.96354047]])

In [25]:
# 使用arange
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# 由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64（浮点数）。

In [29]:
# dtype(数据类型)是一个特殊的对象
# 它含有ndarray将一块内存解释为特定数据类型所需的信息
# 可以在创建ndarray时指定

arr1 = np.array([1,2,3], dtype=np.float64)

arr1.dtype

dtype('float64')

In [30]:
arr2 = np.array([1,2,3],dtype=np.int32)

arr2.dtype

dtype('int32')

In [31]:
# 可以通过ndarray.astype将一个数组从一个dtype转换成另一个dtype

arr = np.array([1,2,3,4,5])

arr.dtype


dtype('int32')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float_arr

array([1., 2., 3., 4., 5.])

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
# 调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。

In [36]:
# Numpy数组的运算

arr = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr - arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr2 = np.array([[0,4,1],[7,2,12]],dtype=np.float64)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [42]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [43]:
# 基本的切片和索引
# 视图上的任何修改都会直接反映到源数组上

arr = np.arange(10)

arr[5:8] = 12

In [44]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]

In [46]:
arr_slice

array([12, 12, 12])

In [47]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [48]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
# 如果想到得到的是ndarray切片的一份副本而非视图
# 需要明确地进行复制操作,例如arr[5:8].copy()


In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][1]

array([4, 5, 6])

In [53]:
arr3d[0,1]

array([4, 5, 6])

In [54]:
# 切片索引

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 单切,切行
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
# 双切,可以切行和列

arr2d[1,:2]

array([4, 5])

In [57]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [58]:
# 对切片表达式的复制操作也会扩散到整个选区

arr2d[:2,1:] = 0

In [59]:
arr2d 

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])